-- 장백수산 배송 중앙관리 시스템 · Supabase SQL Editor에서 전체 실행
-- 실행 후 아래 "최초 관리자 지정" 부분의 이메일만 실제 관리자 이메일로 변경하세요.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'driver' check (role in ('admin', 'driver')),
  employee_code text not null unique,
  full_name text not null,
  phone text not null default '',
  vehicle_number integer check (vehicle_number between 1 and 999),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.driver_daily_status (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  work_date date not null,
  work_state text not null default 'not_started'
    check (work_state in ('not_started', 'working', 'departure_ready', 'delivering', 'completed')),
  delivery_total integer not null default 0,
  delivery_completed integer not null default 0,
  tank_total integer not null default 0,
  tank_loaded integer not null default 0,
  box_total integer not null default 0,
  box_checked integer not null default 0,
  urgent_pending integer not null default 0,
  issue_count integer not null default 0,
  prevented_errors integer not null default 0,
  last_sync_at timestamptz not null default now(),
  unique (driver_id, work_date)
);

create table if not exists public.driver_state_snapshots (
  driver_id uuid not null references public.profiles(id) on delete cascade,
  work_date date not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (driver_id, work_date)
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  driver_id uuid references public.profiles(id) on delete set null,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists driver_daily_status_date_idx
  on public.driver_daily_status (work_date, last_sync_at desc);
create index if not exists activity_logs_driver_idx
  on public.activity_logs (driver_id, created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  );
$$;

create or replace function public.is_active_driver()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'driver' and active = true
  );
$$;

create or replace function public.touch_driver_presence()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_active_driver() then
    raise exception 'active driver account required';
  end if;
  update public.profiles set updated_at = now() where id = auth.uid();
end;
$$;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_active_driver() to authenticated;
grant execute on function public.touch_driver_presence() to authenticated;

alter table public.profiles enable row level security;
alter table public.driver_daily_status enable row level security;
alter table public.driver_state_snapshots enable row level security;
alter table public.activity_logs enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists status_select on public.driver_daily_status;
create policy status_select on public.driver_daily_status
for select to authenticated
using (driver_id = auth.uid() or public.is_admin());

drop policy if exists status_insert on public.driver_daily_status;
create policy status_insert on public.driver_daily_status
for insert to authenticated
with check (
  public.is_admin() or
  (driver_id = auth.uid() and public.is_active_driver())
);

drop policy if exists status_update on public.driver_daily_status;
create policy status_update on public.driver_daily_status
for update to authenticated
using (
  public.is_admin() or
  (driver_id = auth.uid() and public.is_active_driver())
)
with check (
  public.is_admin() or
  (driver_id = auth.uid() and public.is_active_driver())
);

drop policy if exists snapshot_select on public.driver_state_snapshots;
create policy snapshot_select on public.driver_state_snapshots
for select to authenticated
using (driver_id = auth.uid() or public.is_admin());

drop policy if exists snapshot_insert on public.driver_state_snapshots;
create policy snapshot_insert on public.driver_state_snapshots
for insert to authenticated
with check (
  public.is_admin() or
  (driver_id = auth.uid() and public.is_active_driver())
);

drop policy if exists snapshot_update on public.driver_state_snapshots;
create policy snapshot_update on public.driver_state_snapshots
for update to authenticated
using (
  public.is_admin() or
  (driver_id = auth.uid() and public.is_active_driver())
)
with check (
  public.is_admin() or
  (driver_id = auth.uid() and public.is_active_driver())
);

drop policy if exists logs_admin_select on public.activity_logs;
create policy logs_admin_select on public.activity_logs
for select to authenticated
using (public.is_admin());

drop policy if exists logs_authenticated_insert on public.activity_logs;
create policy logs_authenticated_insert on public.activity_logs
for insert to authenticated
with check (
  public.is_admin() or
  (actor_id = auth.uid() and public.is_active_driver())
);

-- 최초 관리자 지정
-- 1) Supabase Dashboard → Authentication → Users에서 관리자 이메일 계정을 먼저 생성
-- 2) 아래 admin@example.com을 실제 관리자 이메일로 바꾸고 이 문장만 다시 실행
insert into public.profiles (
  id, role, employee_code, full_name, vehicle_number, active
)
select id, 'admin', 'admin', '장백수산 관리자', null, true
from auth.users
where email = 'admin@example.com'
on conflict (id) do update set
  role = 'admin',
  employee_code = 'admin',
  full_name = excluded.full_name,
  active = true,
  updated_at = now();

-- Supabase Dashboard → Database → Replication에서 다음 표의 Realtime을 켜세요.
-- profiles, driver_daily_status, driver_state_snapshots
