-- 장백수산 배송 중앙관리 V2 · 기존 V1 위에 그대로 전체 실행할 수 있는 통합 SQL
-- Supabase → SQL Editor → New query → 전체 붙여넣기 → Run

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'driver',
  employee_code text not null unique,
  full_name text not null,
  phone text not null default '',
  vehicle_number integer check (vehicle_number between 1 and 999),
  menu_permissions text[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- V1의 admin/driver 제약을 V2 권한 체계로 확장합니다.
do $$
declare c record;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'public.profiles'::regclass and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    execute format('alter table public.profiles drop constraint %I', c.conname);
  end loop;
exception when undefined_table then null;
end $$;

alter table public.profiles
  add constraint profiles_role_v2_check
  check (role in ('admin','super_admin','dispatch_manager','accounting_manager','field_manager','viewer','driver')) not valid;
alter table public.profiles validate constraint profiles_role_v2_check;
alter table public.profiles add column if not exists menu_permissions text[];

create table if not exists public.driver_daily_status (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  work_date date not null,
  work_state text not null default 'not_started'
    check (work_state in ('not_started','working','departure_ready','delivering','completed')),
  delivery_total integer not null default 0,
  delivery_completed integer not null default 0,
  tank_total integer not null default 0,
  tank_loaded integer not null default 0,
  box_total integer not null default 0,
  box_checked integer not null default 0,
  urgent_pending integer not null default 0,
  issue_count integer not null default 0,
  prevented_errors integer not null default 0,
  last_sync_at timestamptz not null default now(),
  unique (driver_id, work_date)
);

create table if not exists public.driver_state_snapshots (
  driver_id uuid not null references public.profiles(id) on delete cascade,
  work_date date not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (driver_id, work_date)
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  driver_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null default '',
  entity_id text not null default '',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.activity_logs add column if not exists entity_type text not null default '';
alter table public.activity_logs add column if not exists entity_id text not null default '';

create table if not exists public.vehicle_assignments (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  vehicle_number integer not null check (vehicle_number between 1 and 999),
  start_date date not null default current_date,
  end_date date,
  active boolean not null default true,
  note text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date)
);
create unique index if not exists vehicle_assignments_active_vehicle_uq
  on public.vehicle_assignments(vehicle_number) where active = true;
create unique index if not exists vehicle_assignments_active_driver_uq
  on public.vehicle_assignments(driver_id) where active = true;

create table if not exists public.workday_controls (
  work_date date primary key,
  is_closed boolean not null default false,
  closed_at timestamptz,
  closed_by uuid references public.profiles(id) on delete set null,
  close_reason text not null default '',
  backup_status text not null default 'pending'
    check (backup_status in ('pending','healthy','warning','failed')),
  backup_checked_at timestamptz,
  backup_note text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.departure_checks (
  driver_id uuid not null references public.profiles(id) on delete cascade,
  work_date date not null,
  vehicle_number integer not null check (vehicle_number between 1 and 999),
  orders_checked boolean not null default false,
  tanks_checked boolean not null default false,
  boxes_checked boolean not null default false,
  urgent_checked boolean not null default false,
  handover_checked boolean not null default false,
  driver_ready boolean not null default false,
  approved boolean not null default false,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  reject_reason text not null default '',
  updated_at timestamptz not null default now(),
  primary key (driver_id, work_date)
);

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  store_code text not null unique,
  name text not null,
  address text not null default '',
  phone text not null default '',
  contact_name text not null default '',
  assigned_driver_id uuid references public.profiles(id) on delete set null,
  assigned_vehicle integer check (assigned_vehicle between 1 and 999),
  delivery_order integer check (delivery_order between 1 and 999),
  preferred_time text not null default '',
  entry_method text not null default '',
  placement text not null default '',
  prohibited text not null default '',
  parking_note text not null default '',
  handover_note text not null default '',
  access_secret text not null default '',
  photo_urls jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists stores_vehicle_order_idx on public.stores(assigned_vehicle, delivery_order);

create table if not exists public.urgent_orders (
  id bigint generated by default as identity primary key,
  work_date date not null default current_date,
  store_id uuid references public.stores(id) on delete set null,
  store_name text not null default '',
  assigned_driver_id uuid references public.profiles(id) on delete set null,
  assigned_vehicle integer check (assigned_vehicle between 1 and 999),
  item_summary text not null,
  quantity_summary text not null default '',
  note text not null default '',
  priority text not null default 'urgent' check (priority in ('normal','urgent','critical')),
  status text not null default 'new'
    check (status in ('new','acknowledged','loaded','delivered','impossible','cancelled')),
  acknowledged_at timestamptz,
  loaded_at timestamptz,
  delivered_at timestamptz,
  impossible_reason text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists urgent_orders_date_vehicle_idx on public.urgent_orders(work_date, assigned_vehicle, status);

create table if not exists public.incident_reports (
  id bigint generated by default as identity primary key,
  work_date date not null default current_date,
  driver_id uuid references public.profiles(id) on delete set null,
  store_id uuid references public.stores(id) on delete set null,
  vehicle_number integer check (vehicle_number between 1 and 999),
  incident_type text not null check (incident_type in ('wrong_delivery','shortage','excess','damage','band_mismatch','tank_mismatch','delay','other')),
  severity text not null default 'normal' check (severity in ('normal','important','critical')),
  description text not null,
  resolution text not null default '',
  status text not null default 'reported' check (status in ('reported','checking','resolved','closed')),
  photo_urls jsonb not null default '[]'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists incident_reports_date_status_idx on public.incident_reports(work_date, status);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  product_code text not null unique,
  name text not null,
  category text not null check (category in ('활어','패류','냉동제품','필렛 제품','기타')),
  unit text not null check (unit in ('kg','마리','팩','박스','망','봉지','개')),
  origin_country text not null default '국내산',
  base_price numeric(14,2) not null default 0 check (base_price >= 0),
  fillet_fee_per_kg numeric(14,2) not null default 0 check (fillet_fee_per_kg >= 0),
  default_band_color text not null default '',
  effective_from date not null default current_date,
  effective_to date,
  active boolean not null default true,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from)
);

create table if not exists public.product_prices (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  store_id uuid references public.stores(id) on delete cascade,
  unit_price numeric(14,2) not null check (unit_price >= 0),
  fillet_fee_per_kg numeric(14,2) not null default 0 check (fillet_fee_per_kg >= 0),
  effective_from date not null default current_date,
  effective_to date,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from)
);
create index if not exists product_prices_lookup_idx on public.product_prices(product_id, store_id, effective_from desc);

create table if not exists public.invoice_records (
  id uuid primary key default gen_random_uuid(),
  work_date date not null,
  invoice_no text not null,
  driver_id uuid references public.profiles(id) on delete set null,
  vehicle_number integer check (vehicle_number between 1 and 999),
  store_id uuid references public.stores(id) on delete set null,
  store_name text not null default '',
  subtotal numeric(14,2) not null default 0,
  fillet_fee numeric(14,2) not null default 0,
  previous_balance numeric(14,2) not null default 0,
  payment_received numeric(14,2) not null default 0,
  remaining_balance numeric(14,2) not null default 0,
  status text not null default 'issued' check (status in ('draft','issued','revised','cancelled')),
  revision_no integer not null default 1,
  replaces_invoice_id uuid references public.invoice_records(id) on delete set null,
  detail jsonb not null default '{}'::jsonb,
  revision_reason text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (invoice_no, revision_no)
);
create index if not exists invoice_records_date_idx on public.invoice_records(work_date, status);

create table if not exists public.receivable_payments (
  id bigint generated by default as identity primary key,
  work_date date not null,
  store_id uuid references public.stores(id) on delete set null,
  store_name text not null default '',
  previous_balance numeric(14,2) not null default 0,
  payment_received numeric(14,2) not null default 0,
  remaining_balance numeric(14,2) not null default 0,
  note text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.current_staff_role()
returns text language sql stable security definer set search_path=public as $$
  select role from public.profiles where id=auth.uid() and active=true limit 1;
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select coalesce(public.current_staff_role() in ('admin','super_admin','dispatch_manager','accounting_manager','field_manager','viewer'), false);
$$;

create or replace function public.has_permission(permission_name text)
returns boolean language plpgsql stable security definer set search_path=public as $$
declare r text := public.current_staff_role();
begin
  if r in ('admin','super_admin') then return true; end if;
  if r = 'viewer' then return permission_name in ('admin_access','dashboard_read','report_read'); end if;
  if r = 'dispatch_manager' then return permission_name in ('admin_access','dashboard_read','driver_write','account_manage','dispatch_write','store_write','urgent_write','incident_write','departure_write','report_read'); end if;
  if r = 'accounting_manager' then return permission_name in ('admin_access','dashboard_read','product_write','accounting_write','report_read'); end if;
  if r = 'field_manager' then return permission_name in ('admin_access','dashboard_read','store_write','urgent_write','incident_write','departure_write','report_read'); end if;
  return false;
end $$;

create or replace function public.is_active_driver()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='driver' and active=true);
$$;

create or replace function public.current_vehicle_number()
returns integer language sql stable security definer set search_path=public as $$
  select vehicle_number from public.profiles where id=auth.uid() and active=true limit 1;
$$;

create or replace function public.workday_is_open(target_date date)
returns boolean language sql stable security definer set search_path=public as $$
  select not coalesce((select is_closed from public.workday_controls where work_date=target_date),false);
$$;

create or replace function public.touch_driver_presence()
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_active_driver() then raise exception 'active driver account required'; end if;
  update public.profiles set updated_at=now() where id=auth.uid();
end $$;

create or replace function public.prevent_duplicate_driver_vehicle()
returns trigger language plpgsql set search_path=public as $$
begin
  if new.role='driver' and new.active and new.vehicle_number is not null and exists(
    select 1 from public.profiles p where p.id<>new.id and p.role='driver' and p.active and p.vehicle_number=new.vehicle_number
  ) then raise exception '%호차는 이미 다른 배송원에게 배정되어 있습니다.', new.vehicle_number; end if;
  return new;
end $$;
drop trigger if exists profiles_no_duplicate_vehicle on public.profiles;
create trigger profiles_no_duplicate_vehicle before insert or update of role,active,vehicle_number on public.profiles
for each row execute function public.prevent_duplicate_driver_vehicle();

create or replace function public.audit_change()
returns trigger language plpgsql security definer set search_path=public as $$
declare entity text; detail_data jsonb; record_data jsonb;
begin
  record_data := case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
  entity := coalesce(record_data->>'id',record_data->>'work_date',record_data->>'driver_id','');
  detail_data := jsonb_build_object(
    'operation',tg_op,
    'before',case when tg_op in ('UPDATE','DELETE') then to_jsonb(old)-'access_secret' else null end,
    'after',case when tg_op in ('INSERT','UPDATE') then to_jsonb(new)-'access_secret' else null end
  );
  insert into public.activity_logs(actor_id,action,entity_type,entity_id,detail)
  values(auth.uid(),lower(tg_op),tg_table_name,entity,detail_data);
  return case when tg_op='DELETE' then old else new end;
end $$;

do $$ declare t text;
begin
  foreach t in array array['vehicle_assignments','workday_controls','departure_checks','stores','urgent_orders','incident_reports','products','product_prices','invoice_records','receivable_payments']
  loop
    execute format('drop trigger if exists audit_%I on public.%I',t,t);
    execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.audit_change()',t,t);
  end loop;
end $$;

-- 기존 배송원 배정 기록을 가능한 범위에서 자동 생성합니다.
insert into public.vehicle_assignments(driver_id,vehicle_number,start_date,active,note)
select distinct on (p.vehicle_number) p.id,p.vehicle_number,current_date,true,'V1 기존 배정 자동 이관'
from public.profiles p
where p.role='driver' and p.active and p.vehicle_number is not null
  and not exists(select 1 from public.vehicle_assignments a where a.driver_id=p.id and a.active)
order by p.vehicle_number,p.created_at
on conflict do nothing;

-- RLS
do $$ declare t text;
begin
  foreach t in array array['profiles','driver_daily_status','driver_state_snapshots','activity_logs','vehicle_assignments','workday_controls','departure_checks','stores','urgent_orders','incident_reports','products','product_prices','invoice_records','receivable_payments']
  loop execute format('alter table public.%I enable row level security',t); end loop;
end $$;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated using(public.has_permission('driver_write')) with check(public.has_permission('driver_write'));

drop policy if exists status_select on public.driver_daily_status;
create policy status_select on public.driver_daily_status for select to authenticated using(driver_id=auth.uid() or public.is_admin());
drop policy if exists status_insert on public.driver_daily_status;
create policy status_insert on public.driver_daily_status for insert to authenticated with check(public.is_admin() or (driver_id=auth.uid() and public.is_active_driver() and public.workday_is_open(work_date)));
drop policy if exists status_update on public.driver_daily_status;
create policy status_update on public.driver_daily_status for update to authenticated using(public.is_admin() or (driver_id=auth.uid() and public.is_active_driver())) with check(public.is_admin() or (driver_id=auth.uid() and public.is_active_driver() and public.workday_is_open(work_date)));

drop policy if exists snapshot_select on public.driver_state_snapshots;
create policy snapshot_select on public.driver_state_snapshots for select to authenticated using(driver_id=auth.uid() or public.is_admin());
drop policy if exists snapshot_insert on public.driver_state_snapshots;
create policy snapshot_insert on public.driver_state_snapshots for insert to authenticated with check(public.is_admin() or (driver_id=auth.uid() and public.is_active_driver() and public.workday_is_open(work_date)));
drop policy if exists snapshot_update on public.driver_state_snapshots;
create policy snapshot_update on public.driver_state_snapshots for update to authenticated using(public.is_admin() or (driver_id=auth.uid() and public.is_active_driver())) with check(public.is_admin() or (driver_id=auth.uid() and public.is_active_driver() and public.workday_is_open(work_date)));

drop policy if exists logs_admin_select on public.activity_logs;
create policy logs_admin_select on public.activity_logs for select to authenticated using(public.is_admin());
drop policy if exists logs_authenticated_insert on public.activity_logs;
create policy logs_authenticated_insert on public.activity_logs for insert to authenticated with check(public.is_admin() or actor_id=auth.uid());

drop policy if exists assignments_admin_all on public.vehicle_assignments;
create policy assignments_admin_all on public.vehicle_assignments for all to authenticated using(public.is_admin()) with check(public.has_permission('driver_write'));
drop policy if exists assignments_driver_select on public.vehicle_assignments;
create policy assignments_driver_select on public.vehicle_assignments for select to authenticated using(driver_id=auth.uid());

drop policy if exists workday_select on public.workday_controls;
create policy workday_select on public.workday_controls for select to authenticated using(public.is_admin() or public.is_active_driver());
drop policy if exists workday_write on public.workday_controls;
create policy workday_write on public.workday_controls for all to authenticated using(public.has_permission('accounting_write') or public.has_permission('departure_write')) with check(public.has_permission('accounting_write') or public.has_permission('departure_write'));

drop policy if exists departure_select on public.departure_checks;
create policy departure_select on public.departure_checks for select to authenticated using(public.is_admin() or driver_id=auth.uid());
drop policy if exists departure_driver_insert on public.departure_checks;
create policy departure_driver_insert on public.departure_checks for insert to authenticated with check((driver_id=auth.uid() and public.is_active_driver() and approved=false) or public.has_permission('departure_write'));
drop policy if exists departure_driver_update on public.departure_checks;
create policy departure_driver_update on public.departure_checks for update to authenticated using(driver_id=auth.uid() or public.has_permission('departure_write')) with check((driver_id=auth.uid() and approved=false) or public.has_permission('departure_write'));

drop policy if exists stores_select on public.stores;
create policy stores_select on public.stores for select to authenticated using(public.is_admin() or assigned_driver_id=auth.uid() or assigned_vehicle=public.current_vehicle_number());
drop policy if exists stores_write on public.stores;
create policy stores_write on public.stores for all to authenticated using(public.has_permission('store_write')) with check(public.has_permission('store_write'));

drop policy if exists urgent_select on public.urgent_orders;
create policy urgent_select on public.urgent_orders for select to authenticated using(public.is_admin() or assigned_driver_id=auth.uid() or assigned_vehicle=public.current_vehicle_number());
drop policy if exists urgent_admin_write on public.urgent_orders;
create policy urgent_admin_write on public.urgent_orders for all to authenticated using(public.has_permission('urgent_write')) with check(public.has_permission('urgent_write'));
drop policy if exists urgent_driver_update on public.urgent_orders;
create policy urgent_driver_update on public.urgent_orders for update to authenticated using(public.is_active_driver() and (assigned_driver_id=auth.uid() or assigned_vehicle=public.current_vehicle_number())) with check(public.is_active_driver() and (assigned_driver_id=auth.uid() or assigned_vehicle=public.current_vehicle_number()));

drop policy if exists incidents_select on public.incident_reports;
create policy incidents_select on public.incident_reports for select to authenticated using(public.is_admin() or driver_id=auth.uid());
drop policy if exists incidents_admin_write on public.incident_reports;
create policy incidents_admin_write on public.incident_reports for all to authenticated using(public.has_permission('incident_write')) with check(public.has_permission('incident_write'));
drop policy if exists incidents_driver_insert on public.incident_reports;
create policy incidents_driver_insert on public.incident_reports for insert to authenticated with check(public.is_active_driver() and driver_id=auth.uid() and created_by=auth.uid());

drop policy if exists products_select on public.products;
create policy products_select on public.products for select to authenticated using(public.is_admin() or public.is_active_driver());
drop policy if exists products_write on public.products;
create policy products_write on public.products for all to authenticated using(public.has_permission('product_write')) with check(public.has_permission('product_write'));
drop policy if exists prices_select on public.product_prices;
create policy prices_select on public.product_prices for select to authenticated using(public.is_admin() or public.is_active_driver());
drop policy if exists prices_write on public.product_prices;
create policy prices_write on public.product_prices for all to authenticated using(public.has_permission('product_write')) with check(public.has_permission('product_write'));

drop policy if exists invoices_select on public.invoice_records;
create policy invoices_select on public.invoice_records for select to authenticated using(public.is_admin());
drop policy if exists invoices_write on public.invoice_records;
create policy invoices_write on public.invoice_records for all to authenticated using(public.has_permission('accounting_write')) with check(public.has_permission('accounting_write'));
drop policy if exists receivables_select on public.receivable_payments;
create policy receivables_select on public.receivable_payments for select to authenticated using(public.is_admin());
drop policy if exists receivables_write on public.receivable_payments;
create policy receivables_write on public.receivable_payments for all to authenticated using(public.has_permission('accounting_write')) with check(public.has_permission('accounting_write'));

grant execute on function public.current_staff_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.has_permission(text) to authenticated;
grant execute on function public.is_active_driver() to authenticated;
grant execute on function public.current_vehicle_number() to authenticated;
grant execute on function public.workday_is_open(date) to authenticated;
grant execute on function public.touch_driver_presence() to authenticated;

-- 계정·역할·호차는 검증된 관리자 API만 변경하도록 직접 쓰기를 막습니다.
revoke insert, update, delete on public.profiles from authenticated;

-- access_secret은 일반 조회에서 제외합니다. 관리자 서버 API를 거칠 때만 열람·변경됩니다.
revoke select on public.stores from authenticated;
grant select(id,store_code,name,address,phone,contact_name,assigned_driver_id,assigned_vehicle,delivery_order,preferred_time,entry_method,placement,prohibited,parking_note,handover_note,photo_urls,active,updated_by,created_at,updated_at) on public.stores to authenticated;
revoke insert, update, delete on public.stores from authenticated;
grant insert(store_code,name,address,phone,contact_name,assigned_driver_id,assigned_vehicle,delivery_order,preferred_time,entry_method,placement,prohibited,parking_note,handover_note,photo_urls,active,updated_by,created_at,updated_at) on public.stores to authenticated;
grant update(store_code,name,address,phone,contact_name,assigned_driver_id,assigned_vehicle,delivery_order,preferred_time,entry_method,placement,prohibited,parking_note,handover_note,photo_urls,active,updated_by,updated_at) on public.stores to authenticated;

create index if not exists driver_daily_status_date_idx on public.driver_daily_status(work_date,last_sync_at desc);
create index if not exists activity_logs_created_idx on public.activity_logs(created_at desc);

-- 최초 관리자 계정은 기존처럼 role='admin'이어도 모든 권한을 가집니다.
-- 더 세분화하려면 관리자 화면의 '권한·감사' 메뉴에서 역할을 변경하세요.
-- Realtime 권장 표: profiles, driver_daily_status, driver_state_snapshots,
-- urgent_orders, incident_reports, departure_checks, workday_controls
